site_name: Sem's Awesome Blog
site_description: A blogging site built with Material for MkDocs. 
site_url: https://example.com/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
        primary: 
        accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference 
        primary: brown
        accent: amber
         
plugins: 
  - search
  - blog:
       blog_dir: .

       archive_date_format: YYYY
       archive_url_date_format: YYYY

       categories_allowed:
          - Golang
          - Java
          - Python
          - Portfolio
          - Uncategorized
       post_url_format: '{slug}'
  - tags:
       tags_file: tags.md
  - rss:
      match_path: 'blog/*'
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated   

extra:
  social:
    - type: github
      link: "https://github.com/semihbugrasezer"
      icon: "fontawesome/brands/github"

markdown_extensions:
  - attr_list
  - md_in_html
     
   
    
  
 
        
  
               
       

