site_name: sezz.dev
site_description: Personal blog of Semih Buğra Sezer
site_url: https://sezz.dev
site_author: Semih Buğra Sezer
repo_url: https://github.com/semihbugrasezer/mkdocs-sezzdev-blog
repo_name: semihbugrasezer/mkdocs-sezzdev-blog

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
  - git-committers:
      enabled: true
      repository: semihbugrasezer/mkdocs-sezzdev-blog
      branch: main
      token: !ENV GITHUB_TOKEN
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md
  - privacy:
      links: 
      links_attr_map:
        target: _blank
      links_noopener: true
      enabled: true
      assets_exclude:
        - cdn.jsdelivr.net/npm/mathjax@3/*
        - giscus.app/*
  - rss:
      match_path: "posts/.*"
      pretty_print: false
      rss_feed_enabled: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  analytics:
    provider: google
    property: #
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/semihbugrasezer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/semihbugrasezer/

extra_css:
  - stylesheets/extra.css

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2025 <a href="https://github.com/semihbugrasezer"  target="_blank" rel="noopener">Semih Buğra Sezer</a>

nav:
  - index.md
  - Tags: tags.md